### ISSUE TITLE
Bug causing slow SBT start-up

### ISSUE THREAD

**Issue by bwbecker** [sbt/sbt-less#101]
In a clean play-scala-starter-example project (https://github.com/playframework/play-scala-starter-example):

0. Change build.properties to use sbt 0.13.17.
1.  Add file `debug.sbt` containing `logLevel := Level.Debug` to the project directory to enable debugging output from SBT.
2. Add `addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.2")` to plugins.sbt
3. Run `rm -r project/project/ target project/target` to get rid of all compiled artifacts
4. Run `sbt | grep ERROR` and you see four errors such as `CLIENT ERROR: Not Found url=https://repo.typesafe.com/typesafe/ivy-releases/org.webjars.npm/strip-json-comments/`
5. Add `addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.6")` to plugins.sbt
6. Remove the compile artifacts again and rerun `sbt | grep ERROR`.  It reports 112 such errors.

Time to launch sbt goes up from 11 seconds to 52 seconds on my recent high-end MacBook Pro when sbt-less and sbt-jshint are included as plugins.

**Comment by mkurz** [comment]
Looks like this issue was because of slow network or server being slow or a remote repo was not available.
Closing for now. Future artifacts will be hosted on maven central, so I assume this is fixed.
Let me know if you still experience problems.
