### ISSUE TITLE
Update to less v3.8 or higher

### ISSUE THREAD

**Issue by bwbecker** [sbt/sbt-less#117]
sbt-less currently depends on ` "org.webjars" % "less-node" % "2.7.2-1",`.  Is that v. 2.7.2 of less?  Can it be upgraded to less-node v3.8.1, at least?  Less itself is currently at v. 4.1.3.

**Comment by mkurz** [comment]
- #104
- #122 (usable via version [1.5.0](https://github.com/sbt/sbt-less/releases/tag/1.5.0)
- #123 (usable via version [2.0.0](https://github.com/sbt/sbt-less/releases/tag/2.0.0)
