### ISSUE TITLE
better error reporting

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt-less#21]
Current less errors are usually useless. I get something like

```
JsTaskFailure: [object Object] (/home/antonkulaga/denigma/semantic-web/project/target/node-modules/webjars/less/lib/less/parser.js#593) at /home/antonkulaga/denigma/semantic-web/project/target/node-modules/webjars/less/lib/less/parser.js:593 (anonymous)
    at /home/antonkulaga/denigma/semantic-web/project/target/less/sbt-less-1.0.0.jar:77 (anonymous)
...
and so on and so force
```

for each small mistake I have made in one of my less files, I am even not told in which file mistake occured. it does not help me solving the problem. I would like to see a name of the file that is broken with lines of the code that lead to parser failure instead.

**Comment by pjmodi** [comment]
+1 @dejvid

**Comment by huntc** [comment]
PRs are welcome. :-)
