### ISSUE TITLE
LessKeys ignored

### ISSUE THREAD

**Issue by cnrudd** [sbt/sbt-less#48]
Hi,

I'm running playframework 2.3.4., sbt-less 1.0.3

In my build.sbt file, I am setting the following:

LessKeys.compress in Assets := true

LessKeys.sourceMap in Assets := true

LessKeys.sourceMapFileInline in Assets := true

LessKeys.sourceMapLessInline in Assets := true

LessKeys.sourceMapRootpath in Assets := "../../"

Only the first line is being executed.  the css is minified.
the next four appear to be ignored.

no map or less is inlined, and the sourceMapRootpath is not added to the .less urls.

Is anyone else having this trouble?  Any solutions?

Thanks,
Colin

**Comment by eximius313** [comment]
I have exactly the same problem:
```
lazy val root = (project in file(".")).enablePlugins(PlayJava, SbtWeb)

scalaVersion := "2.11.6"

includeFilter in (Assets, LessKeys.less) := "*.less"

LessKeys.sourceMap in Assets := true

LessKeys.cleancss in Assets := true

LessKeys.compress in Assets := true
```
and only ```compress``` is working. Changes in ```.less``` files other than ```main.less``` are not being monitored for nor ```sourceMap``` is being generated

**Comment by michalzubkowicz** [comment]
Still problem here, sourceMap fields are ignored. Any plans fixing this?

**Comment by nremond** [comment]
Same problem here.

@huntc : Try to look into the issue, but getting really lost. Perhaps, could you tell me how to execute the following test : https://github.com/sbt/sbt-js-engine/tree/6d402c4d4791e31c5caea9ab3f76ec58454dc255/src/sbt-test/sbt-js-engine?

**Comment by nremond** [comment]
using sbt-less 1.1.1 fixed the issue for me
