### ISSUE TITLE
add lookup path

### ISSUE THREAD

**Issue by rweng** [sbt/sbt-less#60]
Hi guys,

thanks for this plugin. Is there a way to add a lookup path? For instance, I got the following app structure:

```
- assets
  - stylesheets
    - main.less
    - import.less
  - bower
    - bootstrap
      - less
        - bootstrap.less
```

The import of `import.less` works fine, but I fail at importing the `bootstrap.less`. Ideally, I would like to import it with `@import 'bootstrap/less/bootstrap.less';`, compared to using a relative path to main.less. Is this possible?

Thanks!

**Comment by inetfuture** [comment]
Also curious about this.

**Comment by huntc** [comment]
Yes, something like `lib/bootstrap/bootstrap/less/bootstrap.less`. `lib` is the key. All WebJars etc are available via that path.

**Comment by inetfuture** [comment]
What if there is no corresponding WebJar?

And BTW, do less files have to be in `stylesheets` folder? Is there a way to compile less files in other assets folder like `assets/modules`?

**Comment by huntc** [comment]
> What if there is no corresponding WebJar?

Create one. It is easy. :-)

Anyhow, for Less, there are many versions of it as WebJars. WebJars also now imports directly from Bower.

> And BTW, do less files have to be in stylesheets folder? Is there a way to compile less files in other assets folder like assets/modules?

Anywhere under `assets`.

**Comment by inetfuture** [comment]
> Anywhere under assets.

Yeah, it didn't work before when I only run `activator ~run`, because less files are compiled only after the play application has started

Thanks.

**Comment by huntc** [comment]
> Yeah, it didn't work before when I only run activator ~run, because less files are compiled only after the play application has started

That shouldn't be the case.

**Comment by inetfuture** [comment]
I'm trying to use bower WebJar, after adding it on http://www.webjars.org/bower, got this result:

```
Deployed! 
It will take a few hours for the Maven Central index to update but you should be able to start using the Bower WebJar now. 
GroupID = org.webjars.bower 
ArtifactID = normalize-css 
Version = 3.0.3 
```

I don't understand, if it's not in Maven Central yet, how do use it?

**Comment by lamarios** [comment]
Is it possible to add .less files that are outside of the assets folder ?
I have:
 | app
     | assets
