### ISSUE TITLE
Compile Less files in a module

### ISSUE THREAD

**Issue by agusgambina** [sbt/sbt-less#69]
Hello,

Thank you for this library. I am trying to use in a module that has a playframework 2.3.8. Is it possible? The module is compiling, but seems that is not able to see the less files. 

In other projects less files seems are compiling when I hit the url of the project. But because this is a module, not a project, seems is not working.

Thank you

**Comment by 0xbaadf00d** [comment]
Same issue here, I have split a really big project into little sub-project, Coffee file are compiled to JS and uglify-ed with success. But LESS files are just ignored. The "assets" JAR file only contains .less file (no .css or .min.css files founds).

Im using Play 2.5.x

**Comment by jroper** [comment]
You need to enable the `SbtWeb` plugin for the module to get less compilation happening, and you may also need to explicitly configure less source files in that module.
