### ISSUE TITLE
Dependent compilation is broken since v 1.1.0, worked fine in 1.0.1

### ISSUE THREAD

**Issue by alexflav23** [sbt/sbt-less#81]
Let's assume the following scenario:

`main.less` with the following content:

```less
@import (less) "file1.less"
@import (less) "file2.less"
..
```
In `sbt-less` 1.0.1, a change in any of the dependencies would trigger a full recompilation of `main.less` which is the correct behaviour, given most apps only include one end file. Can this behaviour be restored?

**Comment by stejskal** [comment]
I ran into this too.  Luckily it is fixed in the 1.1.1 code which has been released.  The docs on main page still point people to 1.1.0 however which should probably be fixed so other people do not run into this already fixed issue.

**Comment by alexflav23** [comment]
Hi @stejskal ,

Many thanks for the update, it's very good news this was fixed as I must admitted it was rather inconvenient.
