### ISSUE TITLE
com.typesafe.sbt#sbt-less;1.1.1: not found

### ISSUE THREAD

**Issue by apflieger** [sbt/sbt-less#91]
```
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.1")
```
I can't install the plugin. I tried a bunch of different version but all leads to the error.

Am I missing something ?

**Comment by benmccann** [comment]
1.1.2 has been released. You could see if that works any better for you

**Comment by apflieger** [comment]
hum sorry, I don't use sbt-less anymore :(

**Comment by hayd** [comment]
Using 1.1.2 fixes this for me (this is an issue with sbt 1.0 only).

(Could you push that tag to git also?)
